### ISSUE TITLE
Credentials error using physical machinery

### ISSUE THREAD

**Issue by MarioPalomaresGallego** [kevoreilly/CAPEv2#476]
## This is opensource and you getting __free__ support so be friendly!
* Free support from doomedraven ended, no whiskey no support. For something he updated the documentation :)

# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)
- [ ] I'm have read all configs with all optional parts

# Expected Behavior

Normal execution of cuckoo

# Current Behavior

Root error when using the physical machinery

# Failure Information (for bugs)

I get the following error when launching cuckoo:

[root] CRITICAL: CuckooCriticalError: Physical machine credentials are missing, please add it to the Physical machinery configuration file. 

Previous to this message the only message that is printed is: 

[lib.cuckoo.core.scheduler] INFO: Using "physical" machine manager with max_analysis ....

I have been reading both the issues here and on cuckoo github an didn´t found anything. This error seems pretty weird to me since the physical.conf file does not contain anything related with credentials, and i just filled all the entries that are explained there

## Steps to Reproduce

Set "machinery" to "physical" in the cuckoo.conf
Set the appropiate settings of the physical.conf
python3 cuckoo.py

## Context

| Question         | Answer
|------------------|--------------------
| Git commit       | 2004374
| OS version       | Ubuntu 18.04

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by doomedraven** [comment]
buenas, that probably due to the FOG update? which version of FOG do you use? did you try to comment out that code ? that could be the issue as i see it uses apikey and creds so creds could be from old fog versions
```
# TODO This should be moved to a per-machine thing.
        if not self.options.physical.user or not self.options.physical.password:
            raise CuckooCriticalError(
                "Physical machine credentials are missing, please add it to "
                "the Physical machinery configuration file."
            )
```
https://mariohenkel.medium.com/using-cape-sandbox-and-fog-to-analyze-malware-on-physical-machines-4dda328d4e2c

**Comment by doomedraven** [comment]
hm pretty interesting

1. so that user/password things can be removed no?
2. interesting why it can't get there, our problem that nobody of us having FOG setup to be able to test that
3. about WMI well it stops and starts it so shouldn't fully break FOG client
4. can you please tell me which fog version do you use?

**Comment by kevoreilly** [comment]
I do think we have seen this issue before - I recall discussing it with Mario - the issue is that net stop <service> followed by net start <service> does not restart dependent services which is the problem here I think. We definitely do need the WMI service to be running for a load of stuff to work properly like office docs, but the current method of restarting causes this problem.

I looked into a way of restarting dependent services via the command line and was amazed that such a solution appears not to exist - I do not mean powershell or anything like that as we do not use this, just good old cmd.

However, our discussions eventually led us to the conclusion that there shouldn't be a fog agent running on the machines really as this is just like running VMware Tools or similar on your malware machine - a bad idea as it's so easy to detect. So although it appears to duck the above problem, the best solution in my eyes would be not to rely upon fog agent to do anything, and use physical machinery to switch off and reboot the machine externally.

**Comment by MarioPalomaresGallego** [comment]
@doomedraven @kevoreilly 

- FOG version: 1.5.9.63
- FOG client: 0.12.0

Regarding the user/password issue i do also think that check can be removed, it seems that previous versions of FOG worked with http basic authentication and know they work with API keys, so there is no longer a need for that. Actually this is stange since Mario on it´s commit already mentioned this, seems he forgot to delete that sinppet of code.

The problem of the WMI stopping is what @kevoreilly has just said, dependent services are not restarted. But even if there was a way to restart dependent services the problem of the FOG client is that it also relies on a couple of user processes: FOGTray and FOGUserService (don´t be misslead by the naming), so not only the fog service should be restarted but also these previously menntioned processes.

So @kevoreilly if i am understanding right in order to guarantee that the WMI service is running a restart is performed, why could this be replaced by a normal start. By the way were in the source code can i find the code related to this.

Anyway none of this matters since a deploy task is not being generated by the physical machinery when the analysis ends. I tried to trace the program to the function where this deploy task is executed (/modules/machinery/physical.py stop function) but the code seems to be never reached. I though this code should be called in the 354 line of the scheduler.py line.

**Comment by hariomenkel** [comment]
Greetings! That change with WMI is indeed breaking the interaction with fog if I remember correctly. My blog post was from before this change. I'll resetup my whole CAPE environment tomorrow and check what needs to be fixed so that it works again

**Comment by doomedraven** [comment]
@MarioPalomaresGallego https://github.com/kevoreilly/CAPEv2/blob/master/analyzer/windows/analyzer.py#L507

**Comment by doomedraven** [comment]
i have removed the user/pass check, thanks, lets see if with @hariomenkel help we can upgrade it

**Comment by MarioPalomaresGallego** [comment]
Thanks @doomedraven, @hariomenkel the only piece left for me is the fact that the scheduler does not generate a deploy task.  Deploy task is created on this function
https://github.com/kevoreilly/CAPEv2/blob/90e0d316f96598713d6dc617d6d387ed666da95a/modules/machinery/physical.py#L107
and based on what i have seen this function should be called from here:
https://github.com/kevoreilly/CAPEv2/blob/8b0727aa291d278afd67caeadb28d1c536476001/lib/cuckoo/core/scheduler.py#L354

But i don´t know why it doesn´t get called. I have tried to set a breakpoint here and but it never triggers.

Did you encounter this behaviour @hariomenkel.

**Comment by MarioPalomaresGallego** [comment]
Alright forget about the preovious message, some newbie error by my side. I didn´t know that pdb when used on command line is not able to set breakpoints on a thread code, since the scheduler run tasks on threatds, thats why the breakpoint never triggered. Also i wasn´t able to see the debug messages of cape because i positioning the -d option incorrectly:

python -m pdb <b>-d</b> cuckoo.py
instead of 
python -m pdb cuckoo.py <b>-d</b> 

.... my bad.

Still the task is not being registered on the FOG UI.

**Comment by MarioPalomaresGallego** [comment]
Had a look this morning at the problem i mentioned in the previous message and the problem is that the in the physical.conf file the name of the sections of the file must be the same as the 'label' key within each section. Comments in the conf file does not give you a clear note about this, maybe pointing this out would help.

For my specific case the issue can be almost closed since i have commented the lines that restart the WMI service, and with the correct names in the physical conf file everything works well. 

The only strange thing i have found, just in case someone encounters the same problem, is that on the FOG UI when creating the image for the win7 machine the option "Single Disk (Resizable)" does not work well. The server is able of recording the image but when rebooting the machine it gets stucked on the windows logo. Instead using the option "Multiple Partition Single Disk (Not Resizable)" everything works well. The main drawback of this is that the resulting image is much bigger, actually the same size as the machine disk, which means not only that the machine hosting the FOG server needs a lot of space but also that the upload task takes quite a lot. Interestingly the deploy task is much faster comparing with the upload. For example with my 40 GB win7 machine upload takes about 30 min an deploy 5 min. 

@hariomenkel on your medium post you didn´t have this problem, which windows machine were you using.

@doomedraven i have seen you have removed the credentials check but you left the comment associated to that piece of code.

**Comment by doomedraven** [comment]
Thanks for details, yes i left comment as in case of 2 or more server different apikeys should be used, glad you got it working

**Comment by doomedraven** [comment]
hey guys so to recap before we close this. As far as I know i might be wrong, FOG agent in't required to use FOG, but i think someone told that it wasn't working without FOG agent?

**Comment by kevoreilly** [comment]
I don't know the details of fog but the issues boils down to the question: can these machines be remotely power cycled automatically. If the host can be rebooted externally there is no need for any agent on the host, the next boot should pxe into reimaging. This should be the goal I think here, to remove any unnecessary dependency on agents on the 'guests'.

**Comment by doomedraven** [comment]
thank you all, i did a quick check on thread and it looks like solved, if i missed something reopen
